### ISSUE TITLE
"List index (-1) out of bounds" after clicking "Crack PDF"

### ISSUE THREAD

**Issue by miku86** [tedsmith/PDFCrack-GUI#1]
Hey Ted,

thanks for your efforts!

---

Bug: 
List index (-1) out of bounds. 
Press OK to ignore and risk data corruption. 
Press Abort to kill the program.

---

Reproduction:
1. Open application from terminal: `./pdfcrack-gui`
2. Click `Select PDF` and choose my PDF
3. Click `Crack PDF`
4. The error pops up immediately
5. No additional output in the terminal window

---

Version: 1.2
OS: Arch 5.4.55-1-lts

---

Thank you,
Michael

**Comment by tedsmith** [comment]
Sorry I didn't notice this come in. 

May I ask if you had the option to use a dictionary file? That error usually means it is trying to search through a list.

**Comment by tedsmith** [comment]
Hi

I just tried it using Linux Mint 19.3, kernel 5.4.0-45-generic. 

Opened application by double clicking it
Click Select PDF and choose my password protected PDF
Click Crack PDF

No error popped up. So can I ask more details? I wonder if it is something to do with Arch. I've not used Arch before so I'm not sure if that might be the problem. Are you sure you did not set any of the options? 

![Screenshot at 2020-09-07 13-46-31](https://user-images.githubusercontent.com/1560598/92389236-9f251600-f110-11ea-86ad-35bfec17526f.png)

**Comment by tedsmith** [comment]
Unable to reproduce
